name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22


      - name: Build x86_64
        run: |
          go build -o hello_${{ github.ref_name }}_x86_64 .

      - name: Run x86_64
        run: |
          ./hello_${{ github.ref_name }}_x86_64


      - name: Build arm64
        run: |
          GOOS=darwin GOARCH=arm64 go build -o hello_${{ github.ref_name }}_arm64 .

      - name: Run arm64
        run: |
          ./hello_${{ github.ref_name }}_arm64
