name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22


      - name: Build x86_64 (Intel-based Macs)
        run: |
          go build -o hello_${{ github.ref_name }}_x86_64 .

      - name: Build arm64 (Apple Silicon Macs)
        run: |
          GOOS=darwin GOARCH=arm64 go build -o hello_${{ github.ref_name }}_arm64 .

      - name: Create release_body.txt
        run: |
          cat CHANGELOG.md |grep '0.0.14 ' -A 10000|perl -nalE 'if ($. == 1) { say } else { if (/^\d+\.\d+\.\d+\s+/) { exit } else { say } }' > release_body.txt
          perl -v


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release_body.txt
          files: |
            hello_${{ github.ref_name }}_x86_64
            hello_${{ github.ref_name }}_arm64
